
# parse_ldap_tab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '\xf2.R\xbb\xc3\xea\xaf\xb9\x95\x87 i\xce\xd3<$'

_lr_action_items = {'EOL':([4,],[6,]),'VALUE':([2,],[4,]),'KEY':([0,3,6,],[2,2,-3,]),'$end':([1,3,5,6,],[0,-1,-2,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'input':([0,3,],[1,5,]),'assignment':([0,3,],[3,3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('input',1,'p_input','/home/gjansen/Projects/freeadi/freeadi/config/parse_ldap.py',65),
  ('input',2,'p_input','/home/gjansen/Projects/freeadi/freeadi/config/parse_ldap.py',66),
  ('assignment',3,'p_assignment','/home/gjansen/Projects/freeadi/freeadi/config/parse_ldap.py',73),
]
