
# parse_extini_tab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '\xb6\xdcf`\xb2Q\xb0\x17\xa5\x867\xef\x18K\xe9\xdd'

_lr_action_items = {'LBRACE':([11,],[13,]),'STRING':([1,2,7,10,11,13,14,15,17,],[5,6,6,-4,14,6,-7,-8,-9,]),'EQUALS':([6,],[11,]),'LBRACKET':([0,3,7,8,12,14,15,17,],[1,1,-5,-3,-6,-7,-8,-9,]),'RBRACKET':([5,],[10,]),'$end':([3,4,7,8,9,12,14,15,17,],[-1,0,-5,-3,-2,-6,-7,-8,-9,]),'RBRACE':([7,12,14,15,16,17,],[-5,-6,-7,-8,17,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'section_head':([0,3,],[2,2,]),'assignment':([2,7,13,],[7,7,7,]),'section':([0,3,],[3,3,]),'section_body':([2,7,13,],[8,12,16,]),'subsection':([11,],[15,]),'input':([0,3,],[4,9,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('input',1,'p_input','/home/geert/Projects/freeadi/freeadi/config/parse_extini.py',88),
  ('input',2,'p_input','/home/geert/Projects/freeadi/freeadi/config/parse_extini.py',89),
  ('section',2,'p_section','/home/geert/Projects/freeadi/freeadi/config/parse_extini.py',96),
  ('section_head',3,'p_section_head','/home/geert/Projects/freeadi/freeadi/config/parse_extini.py',100),
  ('section_body',1,'p_section_body','/home/geert/Projects/freeadi/freeadi/config/parse_extini.py',104),
  ('section_body',2,'p_section_body','/home/geert/Projects/freeadi/freeadi/config/parse_extini.py',105),
  ('assignment',3,'p_assignment','/home/geert/Projects/freeadi/freeadi/config/parse_extini.py',112),
  ('assignment',3,'p_assignment','/home/geert/Projects/freeadi/freeadi/config/parse_extini.py',113),
  ('subsection',3,'p_subsection','/home/geert/Projects/freeadi/freeadi/config/parse_extini.py',117),
]
