#
# This file is part of FreeADI. FreeADI is free software and is made available
# under the terms of the GNU General Public License, version 3. Consult the
# file "LICENSE" that is distributed together with this file for the exact
# licensing terms.
#
# FreeADI is copyright (c) 2007 by the FreeADI authors. See the file "AUTHORS"
# for a complete overview.

import re
import time
import socket

from freeadi.config.exception import ConfigWriteError
from freeadi.config.writer import Writer
from freeadi.config.parse_krb5 import Krb5Parser


class Krb5Writer(Writer):
    """Writer for krb5.conf."""

    re_string = re.compile('^' + Krb5Parser.t_STRING + '$')
    re_rvalue_string = re.compile('^' + Krb5Parser.t_rvalue_STRING.__doc__ + '$')

    def _write_header(self, fout):
        fout.write('# krb5.conf generated by FreeADI at %s on %s\n' \
                   % (time.asctime(), socket.gethostname()))
        fout.write('# You may edit this file, but the following will be lost:\n')
        fout.write('# - changes incompatible with FreeADI\n')
        fout.write('# - whitespace, comment and non-relevant ordering changes\n')

    def _write_section_header(self, section, fout, indent=''):
        fout.write('\n[%s]\n' % section)

    def _write_section_body(self, body, fout, indent=''):
        indent += '  '
        for key in body:
            value = body[key]
            if isinstance(value, dict):
                fout.write('%s%s = {\n' % (indent, key))
                self._write_section_body(value, fout, indent)
                fout.write('%s}\n' % indent)
            elif isinstance(value, list):
                for val in value:
                    fout.write('%s%s = %s\n' % (indent, key, val))
            else:
                if not self.re_rvalue_string.match(value):
                    raise ConfigWriteError, 'Illegal value string: %s' % value
                fout.write('%s%s = %s\n' % (indent, key, value))

    def _check_input(self, data):
        for section in data:
            if not self.re_string.match(section):
                raise ConfigWriteError, 'Illegal section name: %s' % section
            self._check_section(data[section])

    def _check_section(self, section):
        for key in section:
            if not self.re_string.match(key):
                raise ConfigWriteError, 'Illegal key name: %s' % key
            value = section[key]
            if isinstance(value, basestring):
                if not self.re_rvalue_string.match(value):
                    raise ConfigWriteError, 'Illegal key value: %s' % value
            elif isinstance(value, list):
                for val in value:
                    if not self.re_rvalue_string.match(val):
                        raise ConfigWriteError, 'Illegal key value: %s' % value
            elif isinstance(value, dict):
                self._check_section(value)

    def write(self, data, fout):
        """Write krb5.conf `data' to stream `fout'."""
        self._check_input(data)
        self._write_header(fout)
        for section in data:
            self._write_section_header(section, fout)
            self._write_section_body(data[section], fout)
